{% set name = "conda-store" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/conda-store/conda-store-{{ version }}.tar.gz
    sha256: 6cd632ff0538e27376cc3c156f12d1cb75cf78687e33451e445e4a70faf49836
    folder: conda-store
  - url: https://pypi.io/packages/source/c/conda-store-server/conda-store-server-{{ version }}.tar.gz
    sha256: fcf10e55f70130dac4aa0d4e342209dbfe34a00058d18fbf95566cbddf558dfc
    folder: conda-store-server

build:
  number: 0

outputs:
  - name: "conda-store"
    version: {{ version }}
    build:
      noarch: python
    script: "build_conda_store.sh"
    requirements:
      host:
        - python >=3.6
        - pip
        - jupyter-packaging
      run:
        - python >=3.6
      run_constrained:
        - {{ pin_subpackage('conda-store-server', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      imports:
        - conda_store

  - name: "conda-store-server"
    version: {{ version }}
    build:
      noarch: python
    script: "build_conda_store_server.sh"
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - conda-docker
        - conda-pack
        - celery
        - flower
        - sqlalchemy
        - requests
        - flask
        - flask-cors
        - pyyaml
        - pydantic
        - traitlets
        - yarl
        - pyjwt
        - minio
      run_constrained:
        - {{ pin_subpackage('conda-store', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      imports:
        - conda_store_server
      commands:
        - conda-store-server --help
        - conda-store-worker --help

about:
  home: https://github.com/Quansight/conda-store
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Conda Environment Management, Builds, and Serve"
  description: |
    End users think in terms of environments not packages. The core
    philosophy of conda-store is to serve identical conda environments
    in as many ways as possible. Conda Store controls the environment
    lifecycle: management, builds, and serving of environments.
  doc_url: https://conda-store.readthedocs.io/
  dev_url: https://github.com/Quansight/conda-store

extra:
  feedstock-name: conda-store
  recipe-maintainers:
    - costrouc
    - jaimergp
