{% set name = "conda-store" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/conda-store/conda-store-{{ version }}.tar.gz
    sha256: 918f513fbad36d09929679d99e23dfd46287031af1bc0b3cafa50cb9ebce4841
    folder: conda-store
  - url: https://pypi.io/packages/source/c/conda-store-server/conda-store-server-{{ version }}.tar.gz
    sha256: a1ad78b5d828befea7b3f213d02ded9808d6bc3fc0e122d2cee9581d3e7b4122
    folder: conda-store-server

build:
  number: 0

outputs:
  - name: "conda-store"
    version: {{ version }}
    build:
      noarch: python
    script: "build_conda_store.sh"
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - aiohttp
        - click
        - python >=3.7
        - rich
        - ruamel.yaml
        - yarl
      run_constrained:
        - {{ pin_subpackage('conda-store-server', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      imports:
        - conda_store
      commands:
        - conda-store --help

  - name: "conda-store-server"
    version: {{ version }}
    build:
      noarch: python
    script: "build_conda_store_server.sh"
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - alembic
        - celery
        - conda-docker
        - conda-pack
        - fastapi
        - filelock
        - itsdangerous
        - jinja2
        - minio
        - pydantic
        - pyjwt
        - python >=3.7
        - python-multipart
        - pyyaml
        - redis-py
        - requests
        - sqlalchemy
        - traitlets
        - uvicorn
        - yarl
      run_constrained:
        - {{ pin_subpackage('conda-store', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      imports:
        - conda_store_server
      commands:
        - conda-store-server --help
        - conda-store-worker --help

about:
  home: https://github.com/Quansight/conda-store
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Conda Environment Management, Builds, and Serve"
  description: |
    End users think in terms of environments not packages. The core
    philosophy of conda-store is to serve identical conda environments
    in as many ways as possible. Conda Store controls the environment
    lifecycle: management, builds, and serving of environments.
  doc_url: https://conda-store.readthedocs.io/
  dev_url: https://github.com/Quansight/conda-store

extra:
  feedstock-name: conda-store
  recipe-maintainers:
    - costrouc
    - jaimergp
