{% set name = "conda-store" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/conda-store/conda-store-{{ version }}.tar.gz
    sha256: 2734f0b6bf1c3c819b5e36e4064b30ce46110ac988cdb9661c5ed4c889ed8497
    folder: conda-store
  - url: https://pypi.io/packages/source/c/conda-store-server/conda-store-server-{{ version }}.tar.gz
    sha256: b8d5602cd9f364c242563c1e2d5e4a8e426d5100dfd3a2ba74160c5dd663d25c
    folder: conda-store-server

build:
  number: 0

outputs:
  - name: "conda-store"
    version: {{ version }}
    build:
      noarch: python
    script: "build_conda_store.sh"
    requirements:
      host:
        - python >=3.6
        - pip
        - jupyter-packaging
      run:
        - python >=3.6
      run_constrained:
        - {{ pin_subpackage('conda-store-server', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      imports:
        - conda_store

  - name: "conda-store-server"
    version: {{ version }}
    build:
      noarch: python
    script: "build_conda_store_server.sh"
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - conda-docker
        - conda-pack
        - celery
        - flower
        - sqlalchemy
        - requests
        - flask
        - flask-cors
        - pyyaml
        - pydantic
        - traitlets
        - yarl
        - pyjwt
        - minio
      run_constrained:
        - {{ pin_subpackage('conda-store', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      imports:
        - conda_store_server
      commands:
        - conda-store-server --help
        - conda-store-worker --help

about:
  home: https://github.com/Quansight/conda-store
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Conda Environment Management, Builds, and Serve"
  description: |
    End users think in terms of environments not packages. The core
    philosophy of conda-store is to serve identical conda environments
    in as many ways as possible. Conda Store controls the environment
    lifecycle: management, builds, and serving of environments.
  doc_url: https://conda-store.readthedocs.io/
  dev_url: https://github.com/Quansight/conda-store

extra:
  feedstock-name: conda-store
  recipe-maintainers:
    - costrouc
    - jaimergp
